export default [
  {
    id: 1,
    slug: 'orebro-katthem',
    thinTitle: 'Örebro ',
    boldTitle: ' Katthem',
    tags: ['website'],
    img: require('../assets/images/orebro-katthem.jpg'),
    compImg: require('../assets/images/computer.jpg'),
    showcase: true,
    excerpt: 'A responsive webpage with admin UI designed to match the workflow of the volunteers.',
  },
  {
    id: 2,
    slug: 'the-climate-report',
    thinTitle: 'The ',
    boldTitle: ' Climate Report',
    tags: ['game'],
    img: require('../assets/images/the-climate-report.jpg'),
    compImg: require('../assets/images/computer.jpg'),
    showcase: true,
    excerpt: 'A game with the goal of highlighting different choices connected to climate change, in a fun and easy way.',
  },
  {
    id: 3,
    slug: 'the-penguin-company',
    thinTitle: 'The ',
    boldTitle: ' Penguin Company',
    tags: ['logotype'],
    img: require('../assets/images/the-penguin-company.jpg'),
    compImg: require('../assets/images/computer.jpg'),
    showcase: true,
    excerpt: 'A logotype designed for a mock-company that sells only penguin costumes.',
  },
  {
    id: 4,
    slug: 'f-w',
    thinTitle: '',
    boldTitle: 'F-W',
    tags: ['logotype'],
    img: require('../assets/images/fw-logo.jpg'),
    compImg: require('../assets/images/computer.jpg'),
    showcase: false,
    excerpt: '',
  },
  {
    id: 5,
    slug: 'mobilatrygghetslarm',
    thinTitle: '',
    boldTitle: 'Mobilatrygghetslarm.se',
    tags: ['website', 'wordpress'],
    img: require('../assets/images/mobilatrygghetslarm.jpg'),
    compImg: require('../assets/images/computer.jpg'),
    showcase: false,
    excerpt: '',
  },
]
