export default [
  {
    id: 1,
    slug: 'orebro-katthem',
    thinTitle: 'Örebro ',
    boldTitle: ' Katthem',
    tags: ['website'],
    img: require('../assets/images/orebro-katthem.jpg'),
    compImg: require('../assets/images/small-orebro-katthem.jpg'),
    showcase: true,
    excerpt: 'A responsive webpage with admin UI designed to match the workflow of the volunteers.',
    longerDesc: '',
    quote: '',
    link: 'https://orebrokatthem.com/',
  },
  {
    id: 2,
    slug: 'the-climate-report',
    thinTitle: 'The ',
    boldTitle: ' Climate Report',
    tags: ['game'],
    img: require('../assets/images/the-climate-report.jpg'),
    compImg: require('../assets/images/small-the-climate-report.jpg'),
    showcase: true,
    excerpt: 'A game with the goal of highlighting different choices connected to climate change, in a fun and easy way.',
    longerDesc: '',
    quote: '',
    link: 'https://game.wallin.design/',
  },
  {
    id: 3,
    slug: 'the-penguin-company',
    thinTitle: 'The ',
    boldTitle: ' Penguin Company',
    tags: ['logotype'],
    img: require('../assets/images/the-penguin-company.jpg'),
    compImg: require('../assets/images/small-the-penguin-company.jpg'),
    showcase: true,
    excerpt: 'A logotype designed for a mock-company that sells only penguin costumes.',
    longerDesc: 'Yeah, you heard that right! This project was made for ' +
      'an assignment during my studies at Kristianstad University. My primary goal was to have fun, just pure fun, and with some ' +
      'inspiration from one very famous lion (aka. Metro Goldwyn Mayers (MGM) logo) I went to work. ' +
      'The logotype is made in Illustrator and has, ofcourse, a black/white version and an inverted black/white version - for maximum use. ' +
      'I got pleasantly surprised by the result, and decided that it would be one of my showcase projects.',
    quote: 'One has to just have fun sometimes, and this is the result.',
    link: '',
  },
  {
    id: 4,
    slug: 'f-w',
    thinTitle: 'F-',
    boldTitle: 'W',
    tags: ['logotype'],
    img: require('../assets/images/fw-logo.jpg'),
    compImg: require('../assets/images/small-f-w.jpg'),
    showcase: false,
    excerpt: '',
    longerDesc: '',
    quote: '',
    link: '',
  },
  {
    id: 5,
    slug: 'mobilatrygghetslarm',
    thinTitle: 'Mobila',
    boldTitle: 'trygghetslarm.se',
    tags: ['website', 'wordpress'],
    img: require('../assets/images/mobilatrygghetslarm.jpg'),
    compImg: require('../assets/images/small-mobilatrygghetslarm.jpg'),
    showcase: false,
    excerpt: '',
    longerDesc: '',
    quote: '',
    link: 'https://mobilatrygghetslarm.se/',
  },
]
