export default [
  {
    id: 1,
    slug: 'orebro-katthem',
    thinTitle: 'Örebro ',
    boldTitle: ' Katthem',
    tags: ['website'],
    img: require('../assets/orebro-katthem.jpg'),
    showcase: true,
    excerpt: 'Text',
  },
  {
    id: 2,
    slug: 'the-climate-report',
    thinTitle: 'The ',
    boldTitle: ' Climate Report',
    tags: ['game'],
    img: require('../assets/the-climate-report.jpg'),
    showcase: true,
    excerpt: 'Text',
  },
  {
    id: 3,
    slug: 'the-penguin-company',
    thinTitle: 'The ',
    boldTitle: ' Penguin Company',
    tags: ['logotype'],
    img: require('../assets/the-penguin-company.jpg'),
    showcase: true,
    excerpt: 'Text',
  },
  {
    id: 4,
    slug: 'f-w',
    thinTitle: '',
    boldTitle: 'F-W',
    tags: ['logotype'],
    img: require('../assets/fw-logo.jpg'),
    showcase: false,
    excerpt: '',
  },
  {
    id: 5,
    slug: 'mobilatrygghetslarm',
    thinTitle: '',
    boldTitle: 'Mobilatrygghetslarm.se',
    tags: ['website', 'wordpress'],
    img: require('../assets/mobilatrygghetslarm.jpg'),
    showcase: false,
    excerpt: '',
  },
]
